### PR TITLE
ignore jest mock functions

### PR DESCRIPTION
**Pull request by tjmehta**

### CODE REVIEW

**Review by suchipi — COMMENTED** [review]
Could you explain the motivation behind this change?

**Comment by tjmehta** [comment]
It’s nice to see jest mock function calls in snapshots. Jest serializes mock functions nicely by default

**Comment by tjmehta** [comment]
I can show you an example if it’ll help

**Comment by tjmehta** [comment]
```js
/// Component

function FooButton ({onClick}) {
  <button onClick={onClick}>Foo</button>
}


/// Test

describe('FooButton', () => {
  it('should handle click', () => {
    const wrapper = mount(<FooButton onClick={jest.fn()} />)
    wrapper.find('button').simulate('click')
    expect(wrapper).toMatchSnapshot()
  })
})


/// Snapshot

exports[`FooButton should handle click 1`] = `
<button
  handleClick={
    [MockFunction] {
      "calls": Array [
        Array [],
      ],
    }
  }
/>
`
```

**Review by suchipi — APPROVED** [review]
Cool, makes sense 👍

**Comment by tjmehta** [comment]
sweet thanks!

**Comment by tjmehta** [comment]
Please lmk when you publish to npm. Thanks, again!

**Comment by suchipi** [comment]
Published in 1.1.0

**Pull request merged**
